#!/bin/bash

trap "exit" SIGINT
trap "exit" SIGTERM

HOSTNAME=$(cat /etc/hostname)
if [ "pg_isready -d postgres -U postgres -h $MAIN_DCW | grep -q 'accepting connections'" ]; then





    EXPORTER=$(PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -AXtqc "SELECT HOST FROM EXPORTERS WHERE HOST='$HOSTNAME'";)

    if [ "$EXPORTER" == "$HOSTNAME" ]; then
        echo "Exporter already exists in database; exit"
    else
                PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "INSERT INTO EXPORTERS \
                (HOST,ACTIVE,DONE) \
                VALUES('$HOSTNAME','true','false');" 
    fi


    while true; do
    check=$(PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -AXtqc "SELECT RUNNING FROM STATE WHERE RUNNING='true'";)
    sleep .5
    
    echo "checking for running"
        if [[ $check == 'true' ]]; then
        echo "state changed to running"    
        PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "UPDATE EXPORTERS SET DONE='false';"
        else
        continue
        fi





        #If exclude is present
        EXCLUDE=/app/EXCLUDE
        if [ -f "$EXCLUDE" ]; then
                EXCLUDE=$(</app/EXCLUDE)
                /app/dockcheck.sh -e $EXCLUDE 
                

                else
        #If exclude is not present
                /app/dockcheck.sh 
                
        fi
    #Insert into database with hostname + containers
            cat GotUpdates.txt | while read -r line ; do
            PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "INSERT INTO CONTAINERS \
            (HOST,NAME,LATEST,ERROR,NEW) \
            VALUES('$HOSTNAME','$line','false','false','true');"
            done
            
            cat NoUpdates.txt | while read -r line ; do
            PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "INSERT INTO CONTAINERS \
            (HOST,NAME,LATEST,ERROR,NEW) \
            VALUES('$HOSTNAME','$line','true','false','false');" 
            done
        
            cat GotErrors.txt  | while read -r line ; do
            PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "INSERT INTO CONTAINERS \
            (HOST,NAME,LATEST,ERROR,NEW) \
            VALUES('$HOSTNAME','$line','false','true','false');" 
            done
            
PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "UPDATE EXPORTERS SET DONE='true';" 
PGPASSWORD=$POSTGRES_PASSWORD psql -h $MAIN_DCW -U postgres -d postgres -c "UPDATE STATE SET RUNNING = 'false';" 
    done

else

echo "Cannot connect to database, check password and connectivity and restart the exporter"

fi







#if [ $? -eq 0 ]; then echo "$(date). ran without error." >> /app/dockcheck.log; else echo "$(date). got errors." >> /app/dockcheck.log ; fi